import { useEffect, useRef, useState } from 'react';
import { judicialTurns, assessTurn, scoreUnits } from '../../lib/consecutiva/judicial.js';
import { cargarVoces, vozElegida, vocesPara, leerPreferencias, guardarPreferencias, hablar, detener } from '../../lib/consecutiva/voz.js';
import { useRecorder } from './useRecorder.js';
import { C, F } from '../../lib/consecutiva/tokens.js';
import { Boton, Tarjeta, Titulo } from './ui.jsx';
const KEY='pj-judicial-attempts-v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||[];}catch{return [];}};
export default function JudicialTrainer({onBack}){
 const [direction,setDirection]=useState('both'),[mode,setMode]=useState('practice'),[idx,setIdx]=useState(0);
 const turns=judicialTurns.filter(t=>direction==='both'||t.language===direction),turn=turns[idx];
 const [text,setText]=useState(''),[notes,setNotes]=useState(''),[rows,setRows]=useState(null),[shown,setShown]=useState(false),[listened,setListened]=useState(false);
 const [speaking,setSpeaking]=useState(false),[voices,setVoices]=useState([]),[audio,setAudio]=useState(null),[error,setError]=useState(''),[transcribing,setTranscribing]=useState(false);
 const [history,setHistory]=useState(read),[session,setSession]=useState({}),[finished,setFinished]=useState(false),[saved,setSaved]=useState(false),[fluency,setFluency]=useState('');
 const [prefs,setPrefs]=useState(leerPreferencias);
 const [highlight,setHighlight]=useState(null);
 const activeWord=useRef(null);
 useEffect(()=>{if(shown&&highlight)activeWord.current?.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});},[shown,highlight]);
 const recognition=useRef(null),textRef=useRef(''),urlRef=useRef(null),generation=useRef(0);
 const recorder=useRecorder();const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
 useEffect(()=>{cargarVoces().then(setVoices);return()=>{generation.current++;detener();recognition.current?.abort();if(urlRef.current)URL.revokeObjectURL(urlRef.current);};},[]);
 const score=rows&&scoreUnits(rows),allRows=Object.values(session).flatMap(x=>x.rows),totalScore=scoreUnits(allRows);
 function reset(){setHighlight(null);generation.current++;detener();recognition.current?.abort();recognition.current=null;setTranscribing(false);setSpeaking(false);setText('');textRef.current='';setNotes('');setRows(null);setShown(false);setListened(false);setSaved(false);setError('');if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=null;setAudio(null);}
 async function listen(){setError('');if(!window.speechSynthesis){setError('Este navegador no puede reproducir la voz. Puedes mostrar el texto y practicar por escrito.');return;}const g=generation.current;setSpeaking(true);setListened(true);await hablar(turn.source,turn.language,vozElegida(voices,turn.language,prefs),prefs.velocidad,position=>{if(g===generation.current)setHighlight(position);});if(g===generation.current){setSpeaking(false);setHighlight(null);}}
 async function record(){setError('');await recorder.iniciar();}
 // Start speech recognition only once the recorder successfully acquired the microphone.
 useEffect(()=>{if(!recorder.grabando||!Recognition)return;let r;try{r=new Recognition();recognition.current=r;r.lang=turn.language==='en'?'es-MX':'en-US';r.continuous=true;r.interimResults=false;r.onresult=e=>{let addition='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)addition+=e.results[i][0].transcript+' ';textRef.current=(textRef.current+' '+addition).trim();setText(textRef.current);setRows(null);};r.onerror=e=>{if(e.error!=='aborted')setError('La transcripción no está disponible. Escucha tu grabación y escribe lo que dijiste.');};r.onend=()=>setTranscribing(false);r.start();setTranscribing(true);}catch{setError('No fue posible transcribir. La grabación sigue activa; puedes escribir tu respuesta después.');}return()=>{r?.stop();};},[recorder.grabando]);
 async function stop(){recognition.current?.stop();setTranscribing(false);const blob=await recorder.detener();if(blob){if(urlRef.current)URL.revokeObjectURL(urlRef.current);const url=URL.createObjectURL(blob);urlRef.current=url;setAudio(url);}}
 function evaluate(){const result=assessTurn(turn,text);setRows(result);setSession(s=>({...s,[turn.id]:{id:turn.id,text,rows:result}}));setSaved(false);}
 function revise(id,status){const result=rows.map(r=>r.id===id?{...r,status}:r);setRows(result);setSession(s=>({...s,[turn.id]:{id:turn.id,text,rows:result}}));setSaved(false);}
 function next(){if(idx===turns.length-1){detener();setFinished(true);}else{reset();setIdx(i=>i+1);}}
 function save(){const data={id:Date.now(),date:new Date().toISOString(),direction,mode,segments:Object.values(session),score:totalScore.value,fluency:fluency===''?null:Number(fluency)};try{const h=[data,...read()].slice(0,30);localStorage.setItem(KEY,JSON.stringify(h));setHistory(h);setSaved(true);}catch{setError('No se pudo guardar el intento: el almacenamiento del navegador está lleno o bloqueado.');}}
 const busy=recorder.grabando||speaking||transcribing;
 const reviewList=history.flatMap(h=>h.segments.flatMap(s=>s.rows.filter(r=>r.status!=='matched').map(r=>({...r,segment:s.id}))));
 return <div style={{fontFamily:F.cuerpo,color:C.tinta,display:'grid',gap:18,fontSize:16,lineHeight:1.6}}>
 <Boton variante="fantasma" disabled={busy} onClick={()=>{reset();onBack();}}>Volver a consecutiva</Boton>
 <div><Titulo>Escucha e interpreta</Titulo><p style={{margin:'8px 0'}}>Consulta con el defensor público</p><details style={{fontSize:14,color:C.suave}}><summary>Cómo se evalúa</summary><p>Nota de práctica. Confirma los resultados dudosos.</p></details></div>
 {!finished&&<>
 <details><summary style={{cursor:"pointer"}}>Dirección y modalidad</summary><Tarjeta><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><label>Dirección<select aria-label="Dirección" disabled={busy} value={direction} onChange={e=>{reset();setDirection(e.target.value);setIdx(0);setSession({});}} style={{display:'block',fontSize:16,padding:10}}><option value="both">Conversación completa</option><option value="en">Inglés → Español</option><option value="es">Español → Inglés</option></select></label><label>Modalidad<select aria-label="Modalidad" disabled={busy||Object.keys(session).length>0} value={mode} onChange={e=>{reset();setMode(e.target.value);}} style={{display:'block',fontSize:16,padding:10}}><option value="practice">Práctica</option><option value="exam">Simulación</option></select></label></div></Tarjeta></details>
 <Tarjeta style={{display:'grid',gap:14}}><span>Segmento {idx+1} de {turns.length} · {turn.speaker}</span><Titulo nivel={2}>{turn.title}</Titulo><strong>Interpreta al {turn.language==='en'?'español':'inglés'}</strong><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Boton onClick={speaking?()=>{generation.current++;detener();setSpeaking(false);setHighlight(null);}:listen} disabled={recorder.grabando||transcribing||(mode==='exam'&&listened&&!speaking)}>{speaking?'Detener audio':'Escuchar'}</Boton>{<Boton variante="secundario" aria-pressed={shown} aria-controls="judicial-source" onClick={()=>{setShown(!shown);setListened(true);}}>{shown?'Ocultar texto':'Mostrar texto'}</Boton>}</div>{shown&&<blockquote id="judicial-source" style={{margin:0,padding:16,borderLeft:`4px solid ${C.azul}`}} lang={turn.language}>{highlight?<>{turn.source.slice(0,highlight.start)}<mark ref={activeWord} style={{background:"#FFE08A",color:"#18334D",borderRadius:4,padding:"2px 0"}}>{turn.source.slice(highlight.start,highlight.end)}</mark>{turn.source.slice(highlight.end)}</>:turn.source}</blockquote>}
 <details><summary>Tomar notas</summary><label>Notas<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} style={{display:'block',width:'100%',padding:12,fontSize:16,boxSizing:'border-box'}}/></label></details>
 <Boton onClick={recorder.grabando?stop:record} disabled={speaking||(!listened&&!recorder.grabando)}>{recorder.grabando?`Detener grabación (${recorder.segundos} s)`:'Grabar interpretación'}</Boton>
 <details style={{fontSize:14,color:C.suave}}><summary>Privacidad</summary><p style={{margin:0}}>{Recognition?'La transcripción puede enviar tu voz al proveedor del navegador.':'Escribe tu respuesta después de grabar.'}</p></details>
 {audio&&<audio controls src={audio} style={{width:'100%'}}/>}
 <details><summary>Ajustar voz</summary><div style={{display:'grid',gap:12,marginTop:12}}><label>Voz<select disabled={busy} value={vozElegida(voices,turn.language,prefs)?.name||''} onChange={e=>{const p={...prefs,[turn.language]:e.target.value};setPrefs(p);guardarPreferencias(p);}} style={{display:'block',maxWidth:'100%',width:'100%',fontSize:16,padding:10}}>{vocesPara(voices,turn.language).map(({voz},i)=><option key={voz.name+voz.lang} value={voz.name}>{voz.name}{i===0?' · recomendada':''}</option>)}</select></label><label>Velocidad<select disabled={busy} value={prefs.velocidad||0.95} onChange={e=>{const p={...prefs,velocidad:Number(e.target.value)};setPrefs(p);guardarPreferencias(p);}} style={{display:'block',fontSize:16,padding:10}}><option value={0.85}>Lenta</option><option value={0.95}>Normal</option><option value={1.05}>Rápida</option></select></label><p style={{fontSize:14,margin:0}}>Voces disponibles en tu teléfono.</p></div></details><label>Tu respuesta<textarea lang={turn.language==='en'?'es':'en'} rows={5} value={text} disabled={recorder.grabando||transcribing} onChange={e=>{textRef.current=e.target.value;setText(e.target.value);setRows(null);setSession(s=>{const n={...s};delete n[turn.id];return n;});}} placeholder="Escribe o revisa tu respuesta." style={{display:'block',width:'100%',padding:12,fontSize:16,boxSizing:'border-box'}}/></label>
 <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Boton onClick={evaluate} disabled={busy||!text.trim()}>{mode==='exam'?'Registrar respuesta':'Evaluar interpretación'}</Boton><Boton variante="secundario" disabled={busy||!rows} onClick={next}>{idx===turns.length-1?'Ver resultado de la sesión':'Siguiente segmento'}</Boton></div>
 {(error||recorder.error)&&<p role="alert" style={{color:C.coral}}>{error||recorder.error}</p>}</Tarjeta>
 {rows&&mode==='practice'&&<Tarjeta style={{display:'grid',gap:14}}><Titulo nivel={2}>{score.value}% · Nota preliminar</Titulo><p style={{margin:0}}>Jurídicas: {score.groups.legal.correct}/{score.groups.legal.total} · Sentido: {score.groups.meaning.correct}/{score.groups.meaning.total}</p><p style={{margin:0,color:C.suave}}>{score.pending} por revisar · {score.critical} cambios de sentido.</p>{rows.map(r=><div key={r.id} style={{borderLeft:`4px solid ${r.status==='matched'?C.verde:r.status==='critical'?C.coral:C.azul}`,padding:'8px 14px',background:C.fondo}}><strong>{r.label}</strong> · {r.kind==='legal'?'Jurídico':'Sentido'}<p style={{margin:'4px 0'}}>{r.status==='matched'?'Detectado':r.status==='critical'?'Error crítico por revisar':r.status==='omission'?'Omisión confirmada':'Revisar'}: {r.reason}</p><p style={{fontSize:14,margin:'4px 0'}}>Equivalencias: {r.accepted.join(' · ')}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Boton variante="fantasma" onClick={()=>revise(r.id,'matched')}>Correcto</Boton><Boton variante="fantasma" onClick={()=>revise(r.id,'omission')}>Omisión</Boton><Boton variante="fantasma" onClick={()=>revise(r.id,'critical')}>Cambio de sentido</Boton></div></div>)}<details><summary>Interpretación sugerida</summary><p>{turn.reference}</p></details><Boton variante="secundario" disabled={busy} onClick={()=>{reset();setSession(s=>{const n={...s};delete n[turn.id];return n;});}}>Repetir segmento</Boton></Tarjeta>}
 </>}
 {finished&&<Tarjeta style={{display:'grid',gap:12}}><Titulo nivel={2}>Resultado de entrenamiento</Titulo><strong style={{fontSize:32}}>{totalScore.value}%</strong><p>Jurídicas: {totalScore.groups.legal.correct}/{totalScore.groups.legal.total} · Sentido: {totalScore.groups.meaning.correct}/{totalScore.groups.meaning.total}</p><p>{totalScore.pending} pendientes de revisión y {totalScore.critical} posibles errores críticos.</p><p style={{fontSize:14}}>Jurídico 60% · Sentido 30% · Fluidez 10% (autoevaluación).</p><label>Fluidez (autoevaluación)<select value={fluency} onChange={e=>{setFluency(e.target.value);setSaved(false);}} style={{fontSize:16,marginLeft:8,padding:8}}><option value="">Sin evaluar</option>{[0,2,4,6,8,10].map(v=><option key={v} value={v}>{v} / 10</option>)}</select></label>{fluency!==''&&<strong>Nota combinada provisional: {Math.round(totalScore.value*.9+Number(fluency))}%</strong>}
 {Object.values(session).map(s=><details key={s.id}><summary>{judicialTurns.find(t=>t.id===s.id).title} · {s.id}</summary><p>Tu respuesta: {s.text}</p><p>Modelo: {judicialTurns.find(t=>t.id===s.id).reference}</p>{s.rows.map(r=><div key={r.id}><strong>{r.label}</strong>: {r.status} · {r.accepted.join(' / ')}<select aria-label={`Revisar ${r.label}`} value={r.status} onChange={e=>{const status=e.target.value;setSession(prev=>({...prev,[s.id]:{...prev[s.id],rows:prev[s.id].rows.map(x=>x.id===r.id?{...x,status}:x)}}));setSaved(false);}}><option value="matched">Correcto</option><option value="review">Pendiente</option><option value="omission">Omisión</option><option value="critical">Cambio de sentido</option></select></div>)}</details>)}
 <Boton disabled={saved} onClick={save}>{saved?'Intento guardado':'Guardar intento'}</Boton>{error&&<p role="alert">{error}</p>}<Boton variante="secundario" onClick={()=>{reset();setFinished(false);setIdx(0);setSession({});setFluency('');}}>Nueva sesión</Boton></Tarjeta>}
 <details><summary>Historial y repaso ({history.length} intentos)</summary>{history.map(h=><p key={h.id}>{new Date(h.date).toLocaleString('es')} · {h.score}% · {h.segments.length} segmentos</p>)}{reviewList.length>0&&<><h3>Términos y unidades por repasar</h3>{Array.from(new Map(reviewList.map(r=>[r.id,r])).values()).map(r=><p key={r.id}><strong>{r.label}</strong>: {r.accepted.join(' · ')}</p>)}</>}</details>
 </div>;
}
